const words = [
  { word: "pineapple", clue: "Tropical fruit" },
  { word: "elephant", clue: "Large animal with a long trunk" },
  { word: "computer", clue: "Electronic device" },
  { word: "giraffe", clue: "Tall animal with a long neck" },
  { word: "chocolate", clue: "Sweet made from cocoa" },
  { word: "piano", clue: "Musical instrument with keys" },
  { word: "tiger", clue: "Wild animal" },
  { word: "emerald", clue: "Type of precious stone" },
  { word: "ship", clue: "Vessel on the sea" },
  { word: "telephone", clue: "Communication device" },
  { word: "forest", clue: "Area with many trees" },
  { word: "square", clue: "Geometric shape with four sides" },
  { word: "bicycle", clue: "Two-wheeled vehicle powered by pedals" },
  { word: "sunflower", clue: "Plant that follows the direction of the sun" },
  { word: "mountain", clue: "Large natural elevation of the land" },
  { word: "ocean", clue: "Vast expanse of saltwater" },
  { word: "book", clue: "Collection of written or printed pages" },
  { word: "dog", clue: "Domestic animal known as man's best friend" },
  { word: "moon", clue: "Natural satellite of the Earth" },
  { word: "airplane", clue: "Means of transport that flies through the air" },
  { word: "chair", clue: "Furniture used for sitting" },
  { word: "clock", clue: "Object that measures time" },
  { word: "window", clue: "Opening in the wall for light and air" },
  { word: "ice cream", clue: "Frozen dessert made from cream or juice" },
  { word: "camera", clue: "Device used to capture images" },
  { word: "rocket", clue: "Spacecraft that travels outside the atmosphere" },
  {
    word: "rainbow",
    clue: "Optical phenomenon with colors of the visible spectrum",
  },
  { word: "guitar", clue: "Stringed musical instrument" },
  { word: "ladder", clue: "Structure used to climb or descend between levels" },
  { word: "lantern", clue: "Portable light source" },
  { word: "pirate", clue: "Adventurer who attacks ships at sea" },
  {
    word: "turtle",
    clue: "Reptile with a shell that lives on land or in the sea",
  },
  { word: "spoon", clue: "Utensil used to eat or serve food" },
  { word: "whale", clue: "Large marine mammal" },
  { word: "helicopter", clue: "Aircraft that takes off and lands vertically" },
  { word: "hammer", clue: "Tool used for hitting or nailing" },
  { word: "pencil", clue: "Writing instrument made of graphite" },
  { word: "butterfly", clue: "Insect with colorful wings" },
  { word: "cactus", clue: "Plant that grows in arid regions" },
  { word: "dinosaur", clue: "Prehistoric extinct animal" },
  { word: "elephant", clue: "Large animal with a long trunk" },
  { word: "rocket", clue: "Spacecraft that travels outside the atmosphere" },
  { word: "guitar", clue: "Stringed musical instrument" },
  { word: "hamburger", clue: "Sandwich with meat and other ingredients" },
  { word: "iceberg", clue: "Large floating block of ice" },
  { word: "tortoise", clue: "Land-dwelling reptile with a shell" },
  { word: "kiwi", clue: "Fruit with brown skin and green interior" },
  { word: "lion", clue: "King of the jungle" },
  { word: "monkey", clue: "Primate that lives in trees" },
  { word: "cloud", clue: "Mass of water vapor in the sky" },
];

export default function getWord() {
  const index = Math.floor(Math.random() * words.length);
  return words[index];
}
